// Anleitung (Hilfe) je Rolle – jede Rolle sieht NUR ihre eigene Anleitung.
// Struktur: GUIDE[sprache][rolle] = [{ t: Titel, s: [Schritte...] }, ...]
export const GUIDE = {
  de: {
    ma: [
      { t: "Anmelden", s: ["Personalnummer oder E-Mail eingeben", "Passwort eingeben – das Auge zeigt es zur Kontrolle an", "Datenschutz bestätigen und auf „Anmelden“ tippen"] },
      { t: "Startbildschirm", s: ["Oben: deine nächste Schicht mit Countdown", "„Deine Einteilung“: dein Arbeitsplatz und wer heute mit dir arbeitet", "Unten: dein Resturlaub in Arbeitstagen"] },
      { t: "Urlaub beantragen", s: ["Mehr → „Urlaub beantragen“", "Im Kalender ersten und letzten Tag antippen", "Kleine Zahl am Tag = so viele Kollegen haben dort schon Urlaub", "„Verbindlich beantragen“ – der Antrag geht an deinen Meister", "Unter „Meine Anträge“: Status sehen, ändern oder zurückziehen"] },
      { t: "Krankmeldung", s: ["Mehr → „Krankmeldung“", "Von-Datum wählen (Bis ist optional)", "Absenden – dein Meister wird informiert", "Die eAU läuft separat über die Krankenkasse"] },
      { t: "Schichtplan", s: ["Tab „Plan“: dein Monatskalender", "Orange = Tagschicht (05:25–17:25), Blau = Nachtschicht (17:25–05:25)", "Genehmigter Urlaub ist grün markiert"] },
      { t: "Lohnzettel", s: ["Tab „Lohn“ öffnen", "Monat antippen → PDF öffnet sich", "Nur du selbst siehst deine Lohnzettel"] },
      { t: "Postfach", s: ["Briefsymbol oben rechts", "Nachricht antippen zum Lesen, „Antworten“ zum Antworten", "„Verfassen“: schreiben geht nur an deine Schichtführung oder Betriebsleitung"] },
      { t: "Einstellungen", s: ["Mehr → „Einstellungen“", "Sprache und Hell/Dunkel umschalten", "Passwort ändern"] },
    ],
    meister: [
      { t: "Anträge freigeben", s: ["Tab „Anträge“: offene Anträge deines Teams", "Urlaub: genehmigen oder ablehnen", "Krankmeldung: zur Kenntnis bestätigen", "Dein eigener Urlaub wird vom Betriebsleiter genehmigt"] },
      { t: "Team", s: ["Tab „Team“: alle Mitarbeiter deiner Schicht", "Status heute: Im Dienst, Frei, Krank oder Urlaub"] },
      { t: "Einteilung", s: ["Tab „Einteilung“ öffnen", "Oben einen Arbeitsplatz antippen (z. B. Messwarte)", "Dann im Raster die Felder antippen – sie färben sich", "Radierer löscht einzelne Felder", "„Erste Spalte auf Woche übernehmen“ spart Zeit", "Urlauber erscheinen automatisch als „Abwesend“"] },
      { t: "Kalender", s: ["Tab „Kalender“: Abwesenheiten deines Teams", "Zahl am Tag = wie viele Personen abwesend sind", "Tag antippen für Details"] },
      { t: "Mitarbeiter anlegen", s: ["Mehr → „Mitarbeiter anlegen“", "Name, E-Mail, Start-Passwort und Personalnummer eintragen", "Entfernen fragt zur Sicherheit nach (Ja/Nein)", "„PDF“ = Abwesenheitsnachweis des Mitarbeiters herunterladen"] },
      { t: "Postfach", s: ["An deine ganze Schicht oder eine einzelne Person", "Unter „Leitung / Personal“: auch an Betriebsleitung und Personalabteilung", "Anhänge möglich (Fotos, PDF, Dateien)"] },
    ],
    bl: [
      { t: "Übersicht", s: ["Kennzahlen: im Dienst gesamt und offene Anträge", "Schicht antippen → Mitarbeiter mit ihrer Einteilung"] },
      { t: "Abwesend", s: ["Alle genehmigten Abwesenheiten deines Betriebs auf einen Blick"] },
      { t: "Anträge", s: ["Alle Anträge des Betriebs im Blick", "Anträge der Schichtmeister genehmigst du (oder dein Assistent)"] },
      { t: "Einteilung", s: ["Tab „Einteilung“: Schicht A–D antippen", "Raster nur ansehen – eingeteilt wird von der Schichtführung"] },
      { t: "Mitarbeiter verwalten", s: ["Mehr → „Mitarbeiter anlegen“", "Rolle und Schicht zuweisen, Schichtwechsel per Auswahl", "Nur Mitarbeiter und Schichtführung (keine Personalabteilung)", "Entfernen mit Sicherheitsabfrage; „PDF“ = Abwesenheitsnachweis"] },
      { t: "Postfach", s: ["An den ganzen Betrieb, eine Schicht oder eine Person", "Unter „Leitung / Personal“: auch an die Personalabteilung"] },
    ],
    hr: [
      { t: "Lohnzettel hochladen", s: ["Tab „Lohnlauf“ öffnen", "Sammel-Upload: Monat wählen und viele PDFs auf einmal – die Personalnummer muss im Dateinamen stehen (z. B. 10007.pdf)", "Das Ergebnis zeigt „zugeordnet“ und „ohne Treffer“", "Einzel-Upload darunter (mit Mitarbeiter-Suche)"] },
      { t: "Betriebe", s: ["Tab „Betriebe“: alle Werke mit kompletter Belegschaft", "Name antippen → Nachricht schreiben, Lohnzettel senden oder Abwesenheitsnachweis (PDF)", "„Leitung anlegen“: Betriebsleiter/Assistent je Betrieb anlegen"] },
      { t: "Anträge & Abwesenheiten", s: ["Tab „Anträge“: wer heute im Dienst oder abwesend ist – über alle Werke", "Darunter alle Urlaubs- und Krankanträge mit Status"] },
      { t: "Postfach", s: ["An alle Betriebe, einen Betrieb, eine Schicht oder eine Person", "Unter „Leitung / Personal“: auch an Betriebsleiter und HR-Kollegen"] },
      { t: "HR-Team", s: ["Mehr → „HR-Team“: neue HR-Kollegen anlegen", "Entfernen deaktiviert das Konto (mit Sicherheitsabfrage)"] },
    ],
  },
  tr: {
    ma: [
      { t: "Giriş", s: ["Personel numarası veya e-posta gir", "Şifreni gir – göz simgesi kontrol için gösterir", "Gizliliği onayla ve „Giriş“e dokun"] },
      { t: "Ana ekran", s: ["Üstte: sıradaki vardiyan ve geri sayım", "„Görev yerin“: iş yerin ve bugün seninle çalışanlar", "Altta: kalan iznin (iş günü)"] },
      { t: "İzin isteme", s: ["Diğer → „İzin talebi“", "Takvimde ilk ve son günü seç", "Gündeki sayı = o gün izinli meslektaş sayısı", "„Bağlayıcı talep et“ – talep amirine gider", "„Taleplerim“ altında: durum, değiştir veya geri çek"] },
      { t: "Hastalık bildirimi", s: ["Diğer → „Hastalık bildirimi“", "Başlangıç tarihini seç (bitiş isteğe bağlı)", "Gönder – amirin bilgilendirilir", "eAU sigorta üzerinden ayrıca gelir"] },
      { t: "Vardiya planı", s: ["„Plan“ sekmesi: aylık takvimin", "Turuncu = gündüz (05:25–17:25), mavi = gece (17:25–05:25)", "Onaylı izin yeşil işaretli"] },
      { t: "Bordro", s: ["„Bordro“ sekmesini aç", "Aya dokun → PDF açılır", "Bordronu sadece sen görürsün"] },
      { t: "Gelen kutusu", s: ["Sağ üstteki zarf simgesi", "Mesaja dokun → oku, „Yanıtla“ ile yanıt ver", "„Yaz“: sadece vardiya amiri veya işletme müdürüne"] },
      { t: "Ayarlar", s: ["Diğer → „Ayarlar“", "Dil ve açık/koyu görünüm", "Şifre değiştirme"] },
    ],
    meister: [
      { t: "Talepleri onayla", s: ["„Talepler“ sekmesi: ekibinin bekleyen talepleri", "İzin: onayla veya reddet", "Hastalık: bilgi olarak onayla", "Kendi iznini işletme müdürü onaylar"] },
      { t: "Ekip", s: ["„Ekip“ sekmesi: vardiyanın tüm çalışanları", "Bugünkü durum: görevde, boş, hasta, izinli"] },
      { t: "Yerleşim", s: ["„Yerleşim“ sekmesini aç", "Üstte bir iş yeri seç (örn. Messwarte)", "Sonra tabloda alanlara dokun – renklenir", "Silgi tek alanı siler", "„İlk sütunu haftaya uygula“ zaman kazandırır", "İzinliler otomatik „Abwesend“ görünür"] },
      { t: "Takvim", s: ["„Takvim“: ekibinin devamsızlıkları", "Gündeki sayı = devamsız kişi sayısı", "Detay için güne dokun"] },
      { t: "Personel ekle", s: ["Diğer → „Personel ekle“", "Ad, e-posta, başlangıç şifresi, personel numarası", "Kaldırma güvenlik sorusu sorar (Evet/Hayır)", "„PDF“ = devamsızlık belgesini indir"] },
      { t: "Gelen kutusu", s: ["Tüm vardiyana veya tek kişiye", "„Yönetim / Personel“ altında: müdür ve İK'ya da", "Ek dosyalar mümkün"] },
    ],
    bl: [
      { t: "Genel bakış", s: ["Rakamlar: görevdeki toplam + bekleyen talepler", "Vardiyaya dokun → çalışanlar ve yerleşimleri"] },
      { t: "Devamsız", s: ["İşletmendeki tüm onaylı devamsızlıklar"] },
      { t: "Talepler", s: ["İşletmenin tüm talepleri", "Vardiya amirlerinin taleplerini sen (veya asistanın) onaylar"] },
      { t: "Yerleşim", s: ["„Yerleşim“: A–D vardiyasını seç", "Sadece görüntüleme – yerleşimi vardiya yönetimi yapar"] },
      { t: "Personel yönetimi", s: ["Diğer → „Personel ekle“", "Rol ve vardiya ata, vardiya değişikliği seçimle", "Sadece çalışan ve vardiya yönetimi (İK yok)", "Kaldırma güvenlik sorulu; „PDF“ = devamsızlık belgesi"] },
      { t: "Gelen kutusu", s: ["Tüm işletmeye, bir vardiyaya veya kişiye", "„Yönetim / Personel“: İK'ya da"] },
    ],
    hr: [
      { t: "Bordro yükleme", s: ["„Bordro“ sekmesini aç", "Toplu yükleme: ay seç + çok PDF – personel numarası dosya adında olmalı (örn. 10007.pdf)", "Sonuç „atandı“ ve „eşleşmedi“ gösterir", "Altta tekli yükleme (aramalı)"] },
      { t: "İşletmeler", s: ["„İşletmeler“: tüm tesisler ve kadro", "İsme dokun → mesaj, bordro veya devamsızlık belgesi (PDF)", "„Yönetim ekle“: işletme başına müdür/asistan"] },
      { t: "Talepler", s: ["„Talepler“: bugün kim görevde/devamsız – tüm tesisler", "Altta tüm izin/hastalık talepleri"] },
      { t: "Gelen kutusu", s: ["Tüm işletmelere, bir işletmeye, vardiyaya veya kişiye", "„Yönetim / Personel“: müdürlere ve İK'ya da"] },
      { t: "İK ekibi", s: ["Diğer → „İK ekibi“: yeni İK çalışanı ekle", "Kaldırma hesabı devre dışı bırakır (güvenlik sorulu)"] },
    ],
  },
  en: {
    ma: [
      { t: "Sign in", s: ["Enter personnel number or email", "Enter password – the eye shows it for checking", "Confirm privacy and tap “Sign in”"] },
      { t: "Home screen", s: ["Top: your next shift with countdown", "“Your assignment”: your workplace and who works with you today", "Bottom: your remaining leave in working days"] },
      { t: "Request leave", s: ["More → “Request leave”", "Tap first and last day in the calendar", "Number on a day = colleagues already on leave", "“Submit bindingly” – goes to your shift supervisor", "Under “My requests”: see status, change or withdraw"] },
      { t: "Report sick", s: ["More → “Report sick”", "Pick start date (end optional)", "Send – your supervisor is informed", "The eAU comes separately from your insurer"] },
      { t: "Shift plan", s: ["“Plan” tab: your monthly calendar", "Orange = day (05:25–17:25), blue = night (17:25–05:25)", "Approved leave is marked green"] },
      { t: "Payslips", s: ["Open the “Pay” tab", "Tap a month → PDF opens", "Only you can see your payslips"] },
      { t: "Inbox", s: ["Envelope icon top right", "Tap a message to read, “Reply” to answer", "“Compose”: only to your shift lead or plant manager"] },
      { t: "Settings", s: ["More → “Settings”", "Switch language and light/dark", "Change password"] },
    ],
    meister: [
      { t: "Approve requests", s: ["“Requests” tab: your team's open requests", "Leave: approve or reject", "Sick note: acknowledge", "Your own leave is approved by the plant manager"] },
      { t: "Team", s: ["“Team” tab: all employees of your shift", "Today's status: on duty, off, sick or leave"] },
      { t: "Assignment", s: ["Open the “Assignment” tab", "Tap a workplace above (e.g. Messwarte)", "Then tap cells in the grid – they get colored", "Eraser clears single cells", "“Apply first column to week” saves time", "People on leave show as “Abwesend” automatically"] },
      { t: "Calendar", s: ["“Calendar”: your team's absences", "Number on a day = how many people are away", "Tap a day for details"] },
      { t: "Add employee", s: ["More → “Add employee”", "Enter name, email, start password, personnel number", "Removing asks for confirmation (Yes/No)", "“PDF” = download the absence record"] },
      { t: "Inbox", s: ["To your whole shift or a single person", "Under “Management / HR”: also to plant manager and HR", "Attachments possible"] },
    ],
    bl: [
      { t: "Overview", s: ["Key figures: on duty and open requests", "Tap a shift → employees with their assignment"] },
      { t: "Absences", s: ["All approved absences of your plant at a glance"] },
      { t: "Requests", s: ["All plant requests in view", "You (or your assistant) approve shift supervisors' requests"] },
      { t: "Assignment", s: ["“Assignment” tab: pick shift A–D", "View only – assigning is done by shift leads"] },
      { t: "Manage employees", s: ["More → “Add employee”", "Assign role and shift, shift change via dropdown", "Only employees and shift leads (no HR)", "Removal asks for confirmation; “PDF” = absence record"] },
      { t: "Inbox", s: ["To the whole plant, a shift or a person", "Under “Management / HR”: also to HR"] },
    ],
    hr: [
      { t: "Upload payslips", s: ["Open the “Payroll” tab", "Bulk upload: pick month + many PDFs – personnel number must be in the file name (e.g. 10007.pdf)", "Result shows “assigned” and “no match”", "Single upload below (with search)"] },
      { t: "Plants", s: ["“Plants” tab: all plants with full workforce", "Tap a name → message, payslip or absence record (PDF)", "“Add management”: plant manager/assistant per plant"] },
      { t: "Requests", s: ["“Requests” tab: who is on duty/absent today – all plants", "Below: all leave/sick requests with status"] },
      { t: "Inbox", s: ["To all plants, one plant, a shift or a person", "Under “Management / HR”: also to managers and HR colleagues"] },
      { t: "HR team", s: ["More → “HR team”: add HR colleagues", "Removing deactivates the account (with confirmation)"] },
    ],
  },
  ru: {
    ma: [
      { t: "Вход", s: ["Введи табельный номер или эл. почту", "Введи пароль – глаз показывает его для проверки", "Подтверди защиту данных и нажми «Войти»"] },
      { t: "Главный экран", s: ["Сверху: следующая смена с обратным отсчётом", "«Твоё назначение»: участок и кто сегодня с тобой", "Внизу: остаток отпуска в рабочих днях"] },
      { t: "Заявка на отпуск", s: ["Ещё → «Заявка на отпуск»", "В календаре выбери первый и последний день", "Число на дне = сколько коллег уже в отпуске", "«Подать заявку» – идёт бригадиру", "В «Мои заявки»: статус, изменить или отозвать"] },
      { t: "Больничный", s: ["Ещё → «Больничный»", "Выбери дату начала (конец опционально)", "Отправь – бригадир будет уведомлён", "eAU приходит отдельно из больничной кассы"] },
      { t: "График смен", s: ["Вкладка «План»: твой календарь", "Оранжевый = день (05:25–17:25), синий = ночь (17:25–05:25)", "Одобренный отпуск отмечен зелёным"] },
      { t: "Расчётные листы", s: ["Открой вкладку «Зарплата»", "Нажми на месяц → откроется PDF", "Твои листы видишь только ты"] },
      { t: "Входящие", s: ["Значок конверта справа вверху", "Нажми на сообщение – читать, «Ответить» – ответ", "«Написать»: только руководству смены или завода"] },
      { t: "Настройки", s: ["Ещё → «Настройки»", "Язык и светлая/тёмная тема", "Смена пароля"] },
    ],
    meister: [
      { t: "Одобрение заявок", s: ["Вкладка «Заявки»: открытые заявки бригады", "Отпуск: одобрить или отклонить", "Больничный: подтвердить", "Твой отпуск одобряет начальник завода"] },
      { t: "Бригада", s: ["Вкладка «Бригада»: все работники смены", "Статус сегодня: на смене, выходной, болен, отпуск"] },
      { t: "Расстановка", s: ["Открой «Расстановка»", "Сверху выбери участок (напр. Messwarte)", "Затем нажимай ячейки – они окрашиваются", "Ластик очищает ячейку", "«Первый столбец на неделю» экономит время", "Отпускники автоматически «Abwesend»"] },
      { t: "Календарь", s: ["«Календарь»: отсутствия бригады", "Число на дне = сколько человек отсутствует", "Нажми на день – детали"] },
      { t: "Добавить сотрудника", s: ["Ещё → «Добавить сотрудника»", "Имя, почта, стартовый пароль, табельный номер", "Удаление спрашивает подтверждение (Да/Нет)", "«PDF» = справка об отсутствии"] },
      { t: "Входящие", s: ["Всей смене или одному человеку", "«Руководство / Кадры»: также начальнику и в HR", "Вложения возможны"] },
    ],
    bl: [
      { t: "Обзор", s: ["Цифры: на смене всего + открытые заявки", "Нажми на смену → работники с расстановкой"] },
      { t: "Отсутствия", s: ["Все одобренные отсутствия завода"] },
      { t: "Заявки", s: ["Все заявки завода", "Заявки бригадиров одобряешь ты (или ассистент)"] },
      { t: "Расстановка", s: ["«Расстановка»: выбери смену A–D", "Только просмотр – расставляет руководство смены"] },
      { t: "Управление персоналом", s: ["Ещё → «Добавить сотрудника»", "Роль и смена, смена смены через выбор", "Только работники и руководство смены (не HR)", "Удаление с подтверждением; «PDF» = справка"] },
      { t: "Входящие", s: ["Всему заводу, смене или человеку", "«Руководство / Кадры»: также в HR"] },
    ],
    hr: [
      { t: "Загрузка листов", s: ["Открой «Зарплата»", "Массовая загрузка: месяц + много PDF – табельный номер в имени файла (напр. 10007.pdf)", "Результат: «назначено» и «без совпадения»", "Ниже одиночная загрузка (с поиском)"] },
      { t: "Заводы", s: ["«Заводы»: все предприятия с персоналом", "Нажми на имя → сообщение, лист или справка (PDF)", "«Добавить руководство»: начальник/ассистент"] },
      { t: "Заявки", s: ["«Заявки»: кто сегодня на смене/отсутствует – все заводы", "Ниже все заявки со статусом"] },
      { t: "Входящие", s: ["Всем заводам, заводу, смене или человеку", "«Руководство / Кадры»: начальникам и коллегам HR"] },
      { t: "Отдел кадров", s: ["Ещё → «Отдел кадров»: добавить коллег", "Удаление отключает аккаунт (с подтверждением)"] },
    ],
  },
  pl: {
    ma: [
      { t: "Logowanie", s: ["Wpisz numer personalny lub e-mail", "Wpisz hasło – oko pokazuje je do kontroli", "Potwierdź ochronę danych i dotknij „Zaloguj się”"] },
      { t: "Ekran główny", s: ["Na górze: następna zmiana z odliczaniem", "„Twój przydział”: stanowisko i kto dziś z Tobą pracuje", "Na dole: pozostały urlop w dniach roboczych"] },
      { t: "Wniosek o urlop", s: ["Więcej → „Wniosek o urlop”", "W kalendarzu dotknij pierwszy i ostatni dzień", "Liczba przy dniu = ilu kolegów ma już urlop", "„Złóż wiążąco” – wniosek idzie do mistrza", "W „Moje wnioski”: status, zmień lub wycofaj"] },
      { t: "Zgłoszenie choroby", s: ["Więcej → „Zgłoś chorobę”", "Wybierz datę od (do opcjonalnie)", "Wyślij – mistrz zostanie poinformowany", "eAU przychodzi osobno z kasy chorych"] },
      { t: "Plan zmian", s: ["Zakładka „Plan”: kalendarz miesięczny", "Pomarańczowy = dzień (05:25–17:25), niebieski = noc (17:25–05:25)", "Zatwierdzony urlop jest zielony"] },
      { t: "Paski wypłat", s: ["Otwórz zakładkę „Płace”", "Dotknij miesiąc → otworzy się PDF", "Swoje paski widzisz tylko Ty"] },
      { t: "Skrzynka", s: ["Ikona koperty u góry po prawej", "Dotknij wiadomość – czytaj, „Odpowiedz” – odpowiedź", "„Napisz”: tylko do kierownictwa zmiany lub zakładu"] },
      { t: "Ustawienia", s: ["Więcej → „Ustawienia”", "Język i jasny/ciemny motyw", "Zmiana hasła"] },
    ],
    meister: [
      { t: "Zatwierdzanie wniosków", s: ["Zakładka „Wnioski”: otwarte wnioski zespołu", "Urlop: zatwierdź lub odrzuć", "Choroba: potwierdź", "Twój urlop zatwierdza kierownik zakładu"] },
      { t: "Zespół", s: ["Zakładka „Zespół”: wszyscy pracownicy zmiany", "Status dziś: na służbie, wolne, chory, urlop"] },
      { t: "Przydział", s: ["Otwórz „Przydział”", "U góry wybierz stanowisko (np. Messwarte)", "Potem dotykaj pól w tabeli – kolorują się", "Gumka czyści pojedyncze pola", "„Pierwsza kolumna na tydzień” oszczędza czas", "Urlopowicze automatycznie „Abwesend”"] },
      { t: "Kalendarz", s: ["„Kalendarz”: nieobecności zespołu", "Liczba przy dniu = ile osób nieobecnych", "Dotknij dzień – szczegóły"] },
      { t: "Dodaj pracownika", s: ["Więcej → „Dodaj pracownika”", "Imię, e-mail, hasło startowe, numer personalny", "Usuwanie pyta o potwierdzenie (Tak/Nie)", "„PDF” = zaświadczenie o nieobecności"] },
      { t: "Skrzynka", s: ["Do całej zmiany lub jednej osoby", "„Kierownictwo / Kadry”: też do kierownika i HR", "Załączniki możliwe"] },
    ],
    bl: [
      { t: "Przegląd", s: ["Liczby: na służbie + otwarte wnioski", "Dotknij zmianę → pracownicy z przydziałem"] },
      { t: "Nieobecni", s: ["Wszystkie zatwierdzone nieobecności zakładu"] },
      { t: "Wnioski", s: ["Wszystkie wnioski zakładu", "Wnioski mistrzów zatwierdzasz Ty (lub asystent)"] },
      { t: "Przydział", s: ["„Przydział”: wybierz zmianę A–D", "Tylko podgląd – przydziela kierownictwo zmiany"] },
      { t: "Zarządzanie kadrą", s: ["Więcej → „Dodaj pracownika”", "Rola i zmiana, zmiana zmiany przez wybór", "Tylko pracownicy i kierownictwo zmiany (bez HR)", "Usuwanie z potwierdzeniem; „PDF” = zaświadczenie"] },
      { t: "Skrzynka", s: ["Do całego zakładu, zmiany lub osoby", "„Kierownictwo / Kadry”: też do HR"] },
    ],
    hr: [
      { t: "Wgrywanie pasków", s: ["Otwórz „Płace”", "Zbiorczo: miesiąc + wiele PDF – numer personalny w nazwie pliku (np. 10007.pdf)", "Wynik: „przypisano” i „brak dopasowania”", "Niżej pojedynczo (z wyszukiwaniem)"] },
      { t: "Zakłady", s: ["„Zakłady”: wszystkie zakłady z załogą", "Dotknij nazwisko → wiadomość, pasek lub zaświadczenie (PDF)", "„Dodaj kierownictwo”: kierownik/asystent"] },
      { t: "Wnioski", s: ["„Wnioski”: kto dziś na służbie/nieobecny – wszystkie zakłady", "Niżej wszystkie wnioski ze statusem"] },
      { t: "Skrzynka", s: ["Do wszystkich zakładów, zakładu, zmiany lub osoby", "„Kierownictwo / Kadry”: do kierowników i kolegów HR"] },
      { t: "Zespół HR", s: ["Więcej → „Zespół HR”: dodaj kolegów HR", "Usunięcie dezaktywuje konto (z potwierdzeniem)"] },
    ],
  },
};
